# hash:sha256:9ca8fa8af4eb9e9b2b7dcd2d02b7cdc4e8a069f8a792f53d834371655da52ca6
FROM registry.codeocean.com/codeocean/stata:16.0-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

COPY stata.lic /usr/local/stata/stata.lic
